name    'icclab-os'
version '0.1.0'
source 'https://github.com/dizz/icclab-os'
author 'Andy Edmonds'
license 'Apache License, Version 2.0'
summary 'Sets up OpenStack Grizzly for the ICCLab'
description 'Sets up OpenStack Grizzly for the ICCLab'
project_page 'https://github.com/dizz/icclab-os'

dependency 'puppetlabs/openstack', '2.1.0'